---
apiVersion: v1
kind: Namespace
metadata:
  name: vinodses-ns
---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  namespace: vinodses-ns
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcontainer
    image: vinodses/my-web-app
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: vinodses-ns
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080

...
