---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapp-replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: vinodses/my-web-app
        ports:
        - containerPort: 8080

...
